[package]
name = "rustsystem-trustauth"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
axum.workspace = true
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
axum-extra = { version = "0.10.1", features = ["cookie"] }
serde.workspace = true
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.4", features = ["cors"] }
tracing = "0.1.41"
uuid = { version = "1.18.1", features = ["serde", "v4"] }

rustsystem-core = { path = "../rustsystem-core" }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
serde_json = "1.0.140"
