/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VoteImport } from './routes/vote'
import { Route as MeetingImport } from './routes/meeting'
import { Route as InviteImport } from './routes/invite'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const VoteRoute = VoteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRoute,
} as any)

const MeetingRoute = MeetingImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRoute,
} as any)

const InviteRoute = InviteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteImport
      parentRoute: typeof rootRoute
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingImport
      parentRoute: typeof rootRoute
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/meeting': typeof MeetingRoute
  '/vote': typeof VoteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/meeting': typeof MeetingRoute
  '/vote': typeof VoteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/meeting': typeof MeetingRoute
  '/vote': typeof VoteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invite' | '/meeting' | '/vote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invite' | '/meeting' | '/vote'
  id: '__root__' | '/' | '/invite' | '/meeting' | '/vote'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  MeetingRoute: typeof MeetingRoute
  VoteRoute: typeof VoteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  MeetingRoute: MeetingRoute,
  VoteRoute: VoteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/invite",
        "/meeting",
        "/vote"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/invite": {
      "filePath": "invite.tsx"
    },
    "/meeting": {
      "filePath": "meeting.tsx"
    },
    "/vote": {
      "filePath": "vote.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
