//! Super-duper vibe-coded!
use anyhow::{Result, anyhow};
use image::{ImageBuffer, Luma};
use rqrr::PreparedImage;
use tiny_skia::{Pixmap, Transform};
use url::Url;
use usvg::{Options, Tree};

/// Decodes the payload from an SVG QR code generated by `qrcode`'s SVG renderer.
pub fn read_qr(svg_str: &str) -> Result<String> {
    // Parse the SVG
    let opt = Options::default();
    let tree = Tree::from_data(svg_str.as_bytes(), &opt).map_err(|_| anyhow!("Invalid SVG"))?;

    // Choose a render size() (upscale if tiny). Your generator used min 200x200,
    // but upscaling increases decoding robustness.
    let vb = tree.size().to_int_size();
    let (mut w, mut h) = (vb.width(), vb.height());
    if w == 0 || h == 0 {
        w = 1024;
        h = 1024;
    } else {
        let scale = (1024.0 / w.max(h) as f32).max(1.0);
        w = ((w as f32) * scale) as u32;
        h = ((h as f32) * scale) as u32;
    }

    // Render with resvg → tiny-skia
    let mut pixmap = Pixmap::new(w, h).ok_or_else(|| anyhow!("Pixmap alloc failed"))?;
    pixmap.fill(tiny_skia::Color::from_rgba8(255, 255, 255, 255)); // white background

    let sx = w as f32 / tree.size().width();
    let sy = h as f32 / tree.size().height();
    let scale = sx.min(sy);
    let tx = (w as f32 - tree.size().width() * scale) * 0.5;
    let ty = (h as f32 - tree.size().height() * scale) * 0.5;
    let transform = Transform::from_translate(tx, ty).post_scale(scale, scale);

    resvg::render(&tree, transform, &mut pixmap.as_mut());

    // RGBA → grayscale
    let rgba = pixmap.data();

    let mut gray = Vec::with_capacity((w * h) as usize);
    for px in rgba.chunks_exact(4) {
        gray.push(px[1]); // just use G
    }

    let img: ImageBuffer<Luma<u8>, _> =
        ImageBuffer::from_raw(w, h, gray).ok_or_else(|| anyhow!("Bad image buffer"))?;

    // Decode (rqrr finds one or more grids; your SVG should be a single QR)
    let mut prepared = PreparedImage::prepare(img.clone());
    for grid in prepared.detect_grids() {
        if let Ok((_, content)) = grid.decode() {
            return Ok(content);
        }
    }

    // Fallbacks are rarely needed for qrcode’s SVGs, but try invert & retry:
    let inverted: ImageBuffer<Luma<u8>, Vec<u8>> = ImageBuffer::from_fn(w, h, |x, y| {
        let p = img.get_pixel(x, y)[0];
        Luma([255u8.saturating_sub(p)])
    });
    let mut prepared_inv = PreparedImage::prepare(inverted);
    for grid in prepared_inv.detect_grids() {
        if let Ok((_, content)) = grid.decode() {
            return Ok(content);
        }
    }

    Err(anyhow!("No QR payload decoded from SVG"))
}

pub fn extract_url_args(url_str: &str) -> Result<(String, String)> {
    let url = Url::parse(url_str).map_err(|e| anyhow!("Invalid URL: {e}"))?;
    let params: std::collections::HashMap<_, _> = url.query_pairs().into_owned().collect();

    let uuuid = params
        .get("uuuid")
        .ok_or_else(|| anyhow!("Missing uuuid"))?
        .to_string();

    let muuid = params
        .get("muuid")
        .ok_or_else(|| anyhow!("Missing muuid"))?
        .to_string();

    Ok((uuuid, muuid))
}

