/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as SignatureDevImport } from "./routes/signature-dev";
import { Route as PreviewImport } from "./routes/preview";
import { Route as MeetingImport } from "./routes/meeting";
import { Route as LoginImport } from "./routes/login";
import { Route as DevTestingImport } from "./routes/dev-testing";
import { Route as CreateMeetingImport } from "./routes/create-meeting";
import { Route as AdminImport } from "./routes/admin";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const SignatureDevRoute = SignatureDevImport.update({
  id: "/signature-dev",
  path: "/signature-dev",
  getParentRoute: () => rootRoute,
} as any);

const PreviewRoute = PreviewImport.update({
  id: "/preview",
  path: "/preview",
  getParentRoute: () => rootRoute,
} as any);

const MeetingRoute = MeetingImport.update({
  id: "/meeting",
  path: "/meeting",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const DevTestingRoute = DevTestingImport.update({
  id: "/dev-testing",
  path: "/dev-testing",
  getParentRoute: () => rootRoute,
} as any);

const CreateMeetingRoute = CreateMeetingImport.update({
  id: "/create-meeting",
  path: "/create-meeting",
  getParentRoute: () => rootRoute,
} as any);

const AdminRoute = AdminImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminImport;
      parentRoute: typeof rootRoute;
    };
    "/create-meeting": {
      id: "/create-meeting";
      path: "/create-meeting";
      fullPath: "/create-meeting";
      preLoaderRoute: typeof CreateMeetingImport;
      parentRoute: typeof rootRoute;
    };
    "/dev-testing": {
      id: "/dev-testing";
      path: "/dev-testing";
      fullPath: "/dev-testing";
      preLoaderRoute: typeof DevTestingImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/meeting": {
      id: "/meeting";
      path: "/meeting";
      fullPath: "/meeting";
      preLoaderRoute: typeof MeetingImport;
      parentRoute: typeof rootRoute;
    };
    "/preview": {
      id: "/preview";
      path: "/preview";
      fullPath: "/preview";
      preLoaderRoute: typeof PreviewImport;
      parentRoute: typeof rootRoute;
    };
    "/signature-dev": {
      id: "/signature-dev";
      path: "/signature-dev";
      fullPath: "/signature-dev";
      preLoaderRoute: typeof SignatureDevImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/create-meeting": typeof CreateMeetingRoute;
  "/dev-testing": typeof DevTestingRoute;
  "/login": typeof LoginRoute;
  "/meeting": typeof MeetingRoute;
  "/preview": typeof PreviewRoute;
  "/signature-dev": typeof SignatureDevRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/create-meeting": typeof CreateMeetingRoute;
  "/dev-testing": typeof DevTestingRoute;
  "/login": typeof LoginRoute;
  "/meeting": typeof MeetingRoute;
  "/preview": typeof PreviewRoute;
  "/signature-dev": typeof SignatureDevRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/create-meeting": typeof CreateMeetingRoute;
  "/dev-testing": typeof DevTestingRoute;
  "/login": typeof LoginRoute;
  "/meeting": typeof MeetingRoute;
  "/preview": typeof PreviewRoute;
  "/signature-dev": typeof SignatureDevRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/create-meeting"
    | "/dev-testing"
    | "/login"
    | "/meeting"
    | "/preview"
    | "/signature-dev";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/create-meeting"
    | "/dev-testing"
    | "/login"
    | "/meeting"
    | "/preview"
    | "/signature-dev";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/create-meeting"
    | "/dev-testing"
    | "/login"
    | "/meeting"
    | "/preview"
    | "/signature-dev";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRoute;
  CreateMeetingRoute: typeof CreateMeetingRoute;
  DevTestingRoute: typeof DevTestingRoute;
  LoginRoute: typeof LoginRoute;
  MeetingRoute: typeof MeetingRoute;
  PreviewRoute: typeof PreviewRoute;
  SignatureDevRoute: typeof SignatureDevRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreateMeetingRoute: CreateMeetingRoute,
  DevTestingRoute: DevTestingRoute,
  LoginRoute: LoginRoute,
  MeetingRoute: MeetingRoute,
  PreviewRoute: PreviewRoute,
  SignatureDevRoute: SignatureDevRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/create-meeting",
        "/dev-testing",
        "/login",
        "/meeting",
        "/preview",
        "/signature-dev"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/create-meeting": {
      "filePath": "create-meeting.tsx"
    },
    "/dev-testing": {
      "filePath": "dev-testing.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/meeting": {
      "filePath": "meeting.tsx"
    },
    "/preview": {
      "filePath": "preview.tsx"
    },
    "/signature-dev": {
      "filePath": "signature-dev.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
