/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PreviewImport } from './routes/preview'
import { Route as DevTestingImport } from './routes/dev-testing'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PreviewRoute = PreviewImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRoute,
} as any)

const DevTestingRoute = DevTestingImport.update({
  id: '/dev-testing',
  path: '/dev-testing',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dev-testing': {
      id: '/dev-testing'
      path: '/dev-testing'
      fullPath: '/dev-testing'
      preLoaderRoute: typeof DevTestingImport
      parentRoute: typeof rootRoute
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-testing': typeof DevTestingRoute
  '/preview': typeof PreviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-testing': typeof DevTestingRoute
  '/preview': typeof PreviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dev-testing': typeof DevTestingRoute
  '/preview': typeof PreviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev-testing' | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev-testing' | '/preview'
  id: '__root__' | '/' | '/dev-testing' | '/preview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevTestingRoute: typeof DevTestingRoute
  PreviewRoute: typeof PreviewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevTestingRoute: DevTestingRoute,
  PreviewRoute: PreviewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dev-testing",
        "/preview"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dev-testing": {
      "filePath": "dev-testing.tsx"
    },
    "/preview": {
      "filePath": "preview.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
